version: '3.7'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: rippleiam
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    build: .
    command: sh -c 'rm -f /myapp/tmp/pids/server.pid && bundle install && bundle exec rails s -p 3000 -b "0.0.0.0"'
    # command: sh -c 'rm -f /myapp/tmp/pids/server.pid && bundle install && bundle exec rails s -p 3000 -b "0.0.0.0"'
    # volumes:
    #   - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - /c/Users/ollie/Documents/ripple-iam:/myapp
      - /myapp/tmp
    environment:
      - RAILS_ENV=development
      - RAILS_LOG_TO_STDOUT=present
      - SECRET_KEY_BASE=b367701b74c339b3baa5d48ae00429eb40a9f2715f57971883d234ea3654a1eb71ca5a266017eef00847f56650b3d07bb53a7fd1b2ca79742dd47ceae840711b
      - KEYCLOAK_BASE_URL=http://sso:8080
      - KEYCLOAK_REALM=ripple
      - KEYCLOAK_CLIENT_ID=ripple-iam-service
      - KEYCLOAK_CLIENT_SECRET=4572b16c-71ff-4992-8b27-cefd8a67fda8
      - AIRBRAKE_PROJECT_ID=277593
      - AIRBRAKE_PROJECT_KEY=03b80add684a295669903907006fd86a
      - RABBIT_HOSTNAME=rabbit
      - RABBIT_PORT=5672
      - RABBIT_USER=ripple-iam
      - RABBIT_PASSWORD=ripple-iam
      - RABBIT_EXCHANGE=ripple
    restart: always
  sso:
    image: jboss/keycloak:10.0.2
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      DB_VENDOR: postgres
      DB_ADDR: db
      DB_PORT: 5432
      DB_USER: rippleiam
      DB_PASSWORD: password
    volumes:
      - sso_data:/var/lib/postgresql/data
    ports:
      - "8080:8080"
    depends_on:
      - db
  rabbit:
    image: rabbitmq:3.8.4-management-alpine
    volumes:
      - bunny_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
volumes:
  postgres_data:
  sso_data:
  bunny_data:
